apiVersion: v1
kind: Service
metadata:
  name: kuber-service
  labels: 
    app: kuber
spec:
  selector:
    app: kuber
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-v1
  labels:
    app: kuber
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kuber
      version: v1.0
  template:
    metadata:
      labels:
        app: kuber
        version: v1.0
    spec:
      containers:
      - name: kuber
        image: bokovets/kuber:v1.0
        ports:
        - containerPort: 8000
