apiVersion: v1
kind: Service
metadata:
  name: kuber-service
  labels:
    app: kuber
spec:
  selector:
    app: kuber
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber
  labels:
    app: kuber
spec:
  replicas: 5
  minReadySeconds: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kuber
  template:
    metadata:
      labels:
        app: kuber
    spec:
      containers:
      - name: kuber
        image: bokovets/kuber:v1.0
        ports:
        - containerPort: 8000
