apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber
  labels:
    app: kuber
spec:
  replicas: 5
  minReadySeconds: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kuber
  template:
    metadata:
      labels:
        app: kuber
    spec:
      containers:
      - name: kuber
        image: bokovets/kuber:v2.0
        ports:
        - containerPort: 8000
